# Generated by Django 5.2.14 on 2026-06-05 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_closed_period_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(help_text='Internal bill number, unique per entity.', max_length=64)),
                ('external_bill_number', models.CharField(blank=True, help_text='External bill number from API source, if applicable.', max_length=255)),
                ('date', models.DateField()),
                ('due_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total bill amount, should match sum of line amounts.', max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('voided', 'Voided')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='accounting.entity')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('customer_code', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_ar_account', models.ForeignKey(blank=True, help_text='Default AR account for invoices created for this customer. Can be overridden per invoice line.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers_with_default_ar', to='accounting.account')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='accounting.entity')),
            ],
            options={
                'ordering': ['customer_code'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Internal invoice number, unique per entity.', max_length=64)),
                ('external_invoice_number', models.CharField(blank=True, help_text='External invoice number from API source, if applicable.', max_length=255)),
                ('date', models.DateField()),
                ('due_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total invoice amount, should match sum of line amounts.', max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('voided', 'Voided')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounting.customer')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='accounting.entity')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(help_text='Account to credit when this line is posted. Usually revenue account.', on_delete=django.db.models.deletion.PROTECT, to='accounting.account')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.invoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('invoice', 'Customer Invoice'), ('bill', 'Vendor Bill')], help_text='Whether this payment is for an invoice or bill.', max_length=16)),
                ('source_id', models.PositiveIntegerField(help_text='ID of the Invoice or Bill being paid.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(help_text='Cash/bank account to debit (for invoice) or credit (for bill).', on_delete=django.db.models.deletion.PROTECT, to='accounting.account')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounting.entity')),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(blank=True, help_text='Bill being paid, if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_applications', to='accounting.bill')),
                ('invoice', models.ForeignKey(blank=True, help_text='Invoice being paid, if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_applications', to='accounting.invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounting.payment')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vendor_code', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_ap_account', models.ForeignKey(blank=True, help_text='Default AP account for bills created for this vendor. Can be overridden per bill line.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendors_with_default_ap', to='accounting.account')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendors', to='accounting.entity')),
            ],
            options={
                'ordering': ['vendor_code'],
            },
        ),
        migrations.CreateModel(
            name='CreditMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('customer', 'Customer Credit'), ('vendor', 'Vendor Credit')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('memo_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_memos', to='accounting.entity')),
                ('customer', models.ForeignKey(blank=True, help_text='Customer for customer credits.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_memos', to='accounting.customer')),
                ('vendor', models.ForeignKey(blank=True, help_text='Vendor for vendor credits.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_memos', to='accounting.vendor')),
            ],
            options={
                'ordering': ['-memo_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='accounting.vendor'),
        ),
        migrations.CreateModel(
            name='BillLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(help_text='Account to debit when this line is posted. Usually expense or asset account.', on_delete=django.db.models.deletion.PROTECT, to='accounting.account')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.bill')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='bill_line_positive_amount')],
            },
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('entity', 'customer_code'), name='unique_customer_code_per_entity'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('entity', 'invoice_number'), name='unique_invoice_number_per_entity'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('external_invoice_number__gt', '')), fields=('entity', 'external_invoice_number'), name='unique_external_invoice_number_per_entity'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='invoice_line_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='paymentapplication',
            constraint=models.CheckConstraint(condition=models.Q(('applied_amount__gt', 0)), name='payment_application_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='vendor',
            constraint=models.UniqueConstraint(fields=('entity', 'vendor_code'), name='unique_vendor_code_per_entity'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(fields=('entity', 'bill_number'), name='unique_bill_number_per_entity'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(condition=models.Q(('external_bill_number__gt', '')), fields=('entity', 'external_bill_number'), name='unique_external_bill_number_per_entity'),
        ),
    ]
