# Generated by Django 5.2.15 on 2026-06-11 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_bankaccount_bankreconciliation_bankstatementline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='account',
            field=models.ForeignKey(help_text='Account associated with the payment record while funds are undeposited.', on_delete=django.db.models.deletion.PROTECT, to='accounting.account'),
        ),
    ]
