# Generated by Django 5.2.15 on 2026-06-11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0006_alter_payment_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportView",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                (
                    "report_type",
                    models.CharField(
                        choices=[("balance_sheet", "Balance Sheet"), ("profit_and_loss", "Profit and Loss")],
                        max_length=32,
                    ),
                ),
                (
                    "basis",
                    models.CharField(
                        choices=[("accrual", "Accrual"), ("cash", "Cash")],
                        default="accrual",
                        max_length=16,
                    ),
                ),
                ("as_of_date", models.DateField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("display_settings", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_report_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_views",
                        to="accounting.entity",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="TaxCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("rate", models.DecimalField(decimal_places=4, help_text="Tax rate expressed as a decimal fraction.", max_digits=7)),
                (
                    "jurisdiction",
                    models.CharField(
                        choices=[("us", "United States"), ("ca", "California")],
                        default="us",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tax_codes",
                        to="accounting.entity",
                    ),
                ),
                (
                    "liability_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tax_codes",
                        to="accounting.account",
                    ),
                ),
            ],
            options={
                "ordering": ["code", "id"],
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="is_credit_adjustment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="reportview",
            constraint=models.UniqueConstraint(fields=("entity", "name"), name="unique_report_view_name_per_entity"),
        ),
        migrations.AddConstraint(
            model_name="taxcode",
            constraint=models.UniqueConstraint(fields=("entity", "code"), name="unique_tax_code_per_entity"),
        ),
    ]
