# Generated by Django 5.2.15 on 2026-06-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0007_reportview_taxcode_payment_credit_adjustment"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="external_source_client_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="External API client identifier that supplied the external invoice number.",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="external_source_client_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="External API client identifier that supplied the external bill number.",
                max_length=128,
            ),
        ),
        migrations.CreateModel(
            name="ApiRequestRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("client_id", models.CharField(max_length=128)),
                ("event_type", models.CharField(max_length=128)),
                ("idempotency_key", models.CharField(max_length=255)),
                ("nonce", models.CharField(max_length=255)),
                ("request_hash", models.CharField(max_length=64)),
                ("request_payload", models.JSONField(default=dict)),
                ("response_status_code", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("domain_object_type", models.CharField(blank=True, default="", max_length=128)),
                ("domain_object_id", models.CharField(blank=True, default="", max_length=64)),
                ("journal_entry_id", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="api_request_records",
                        to="accounting.entity",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="invoice",
            name="unique_external_invoice_number_per_entity",
        ),
        migrations.RemoveConstraint(
            model_name="bill",
            name="unique_external_bill_number_per_entity",
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_invoice_number__gt", "")),
                fields=("entity", "external_source_client_id", "external_invoice_number"),
                name="unique_external_invoice_number_per_client_per_entity",
            ),
        ),
        migrations.AddConstraint(
            model_name="bill",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_bill_number__gt", "")),
                fields=("entity", "external_source_client_id", "external_bill_number"),
                name="unique_external_bill_number_per_client_per_entity",
            ),
        ),
        migrations.AddConstraint(
            model_name="apirequestrecord",
            constraint=models.UniqueConstraint(
                fields=("entity", "client_id", "event_type", "idempotency_key"),
                name="unique_api_request_idempotency_per_client_entity_event",
            ),
        ),
        migrations.AddConstraint(
            model_name="apirequestrecord",
            constraint=models.UniqueConstraint(fields=("client_id", "nonce"), name="unique_api_request_nonce_per_client"),
        ),
    ]
