# Generated by hand to mirror the generic sync-event boundary.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0008_api_request_record_external_source_client_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncEventRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_system", models.CharField(max_length=128)),
                ("domain_event_type", models.CharField(max_length=128)),
                ("external_id", models.CharField(max_length=255)),
                ("source_object_type", models.CharField(max_length=128)),
                ("source_object_id", models.CharField(max_length=128)),
                ("idempotency_key", models.CharField(max_length=255)),
                ("request_hash", models.CharField(max_length=64)),
                ("occurred_at", models.DateTimeField()),
                ("payload", models.JSONField(default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("received", "Received"), ("processed", "Processed"), ("failed", "Failed")],
                        default="received",
                        max_length=16,
                    ),
                ),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sync_event_records",
                        to="accounting.entity",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="synceventrecord",
            constraint=models.UniqueConstraint(
                fields=("entity", "source_system", "domain_event_type", "idempotency_key"),
                name="unique_sync_event_idempotency_per_source_event",
            ),
        ),
        migrations.AddConstraint(
            model_name="synceventrecord",
            constraint=models.UniqueConstraint(
                fields=("entity", "source_system", "domain_event_type", "external_id"),
                name="unique_sync_event_external_id_per_source_event",
            ),
        ),
    ]
