# Generated by Django 5.2.15 on 2026-07-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0009_sync_event_record"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="account",
            field=models.ForeignKey(
                help_text="Cash/bank account used to fund the payment.",
                on_delete=django.db.models.deletion.PROTECT,
                to="accounting.account",
            ),
        ),
    ]
